title = "Randy"
baseURL = 'https://randy.gg'
languageCode = 'en-us'
theme = 'lugo'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  #relatedtext = "Related:"
  #favicon = "/favicon.ico"
  showrss = true
  description = "Lorem ipsum dolor sit amet. In enim voluptatem ut officia voluptatem est debitis eius. Ad quis aspernatur et impedit internos est fugit assumenda in asperiores dicta et quisquam suscipit non cupiditate beatae eum fugit impedit."

[markup.goldmark.renderer]
  unsafe= true