title = "randy.gg"
baseURL = 'https://randy.gg'
languageCode = 'en-us'
theme = 'lugo'

# Feel free to adjust these Parameters as you need :D
[params]
  #favicon = "/favicon.ico"
  showrss = true

  youtube_link = "https://www.youtube.com/@randyprime"
  kofi_link = "https://ko-fi.com/bigrando420"
  twitch_link = "https://twitch.tv/randy"

  contact_email = "contact@randy.gg"
  
  web_description = "I'm just a dude who's trying his best to become a solid game developer and decent human being somewhere along the way. Follow My Journey."
  intro_description = "G’DAY, I’m Randy"




[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
  unsafe= true
  hardWraps = true

[params.fonts]
  google_fonts = false

  